/* ad_uti.h -- the FileType a SENDER declares in /Ask, decided without guessing.
 *
 * /Ask carries FileType as an Apple Uniform Type Identifier -- "public.png" off the wire
 * from a real macOS sender -- and NOT as a MIME type. An
 * Arduino sketch is far more likely to know "image/png": every ESP32 web server speaks
 * MIME and none speaks UTI. So the public field takes either, told apart by the one
 * character a UTI never contains and a MIME type always does: '/'.
 *
 * THE TABLE BELOW IS NOT THIS PROJECT'S MEASUREMENT AND DOES NOT PRETEND TO BE. Every pair
 * was read back from Apple's own UniformTypeIdentifiers framework on a Mac --
 * UTType(mimeType:).identifier, regenerated by tools/gen_uti_golden.sh -- which is an
 * implementation nobody here wrote, the standard tools/test-bplist.sh holds itself to with
 * plistlib and tools/test-pack.sh with cpio(1). What a row says is "this is the identifier
 * Apple's own system uses for that MIME type". What it does NOT say is that a peer accepts
 * it in /Ask. Two rows have been on this wire: public.png, to both platforms (203 iPhone
 * and 147 Mac completed sends), and public.jpeg, to a Mac only (270-314 KB captured
 * photos). Every other row is unmeasured there, and so is any row to an iPhone but the
 * first; the library sends them because the caller asked, not because it knows.
 *
 * A MIME type the table does not know is REFUSED, not encoded. macOS answers an unknown
 * MIME type with a dynamic identifier -- "dyn.ah62d4rv4gq80c6durvy0g2pyrf106p5hsb6c08drru"
 * for application/gpx+xml, read back the same way -- and that encoding is undocumented and
 * untested here. A caller who has the real UTI passes it directly.
 *
 * NOTHING HERE READS A FILENAME EXTENSION, on purpose. The same framework maps ".bin" to
 * com.apple.macbinary-archive: a sketch sending "data.bin" would have its bytes declared
 * as a 1985 Mac archive format. A table that can be that wrong for the most ordinary name
 * is not a table this library should carry. The bytes are the only thing that can be
 * checked without a second table, and they are.
 *
 * Dependency-free C, in the house style: the same code compiles into the firmware and
 * into tools/test-uti.sh. The table is const, so it lives in flash, not internal RAM.
 */
#pragma once
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>
#include "ad_cpio.h"     /* ad_cpio_sniff() and AD_FILE_* -- the same sniffer the receiver uses */

/* Longest UTI this will pass through. Apple's own longest common identifiers run to about
   60 characters (org.openxmlformats.wordprocessingml.document is 44); 127 leaves room and
   keeps the bplist size byte single (ad_bpw_size takes 0x10 + one byte below 256). */
#define AD_UTI_MAX 127

struct AdUtiRow { const char *mime; const char *uti; };

/* READ BACK FROM UTType(mimeType:) ON macOS 26 (Darwin 25.6.0), none dynamic.
   Keep in step with tools/gen_uti_golden.sh; the host test compares the two. */
static const struct AdUtiRow ad_uti_table[] = {
  { "image/png",                 "public.png"                         },   /* the one on the wire */
  { "image/jpeg",                "public.jpeg"                        },
  { "image/gif",                 "com.compuserve.gif"                 },
  { "image/heic",                "public.heic"                        },
  { "image/heif",                "public.heif"                        },
  { "image/webp",                "org.webmproject.webp"               },
  { "image/bmp",                 "com.microsoft.bmp"                  },
  { "image/tiff",                "public.tiff"                        },
  { "image/svg+xml",             "public.svg-image"                   },
  { "application/pdf",           "com.adobe.pdf"                      },
  { "application/zip",           "public.zip-archive"                 },
  { "application/json",          "public.json"                        },
  { "application/xml",           "public.xml"                         },
  { "text/xml",                  "public.xml"                         },
  { "text/plain",                "public.plain-text"                  },
  { "text/html",                 "public.html"                        },
  { "text/csv",                  "public.comma-separated-values-text" },
  { "text/vcard",                "public.vcard"                       },
  { "text/calendar",             "com.apple.ical.ics"                 },
  { "text/markdown",             "net.daringfireball.markdown"        },
  { "audio/mpeg",                "public.mp3"                         },
  { "audio/wav",                 "com.microsoft.waveform-audio"       },
  { "audio/x-wav",               "com.microsoft.waveform-audio"       },
  { "audio/mp4",                 "public.mpeg-4-audio"                },
  { "audio/x-m4a",               "com.apple.m4a-audio"                },
  { "video/mp4",                 "public.mpeg-4"                      },
  { "video/quicktime",           "com.apple.quicktime-movie"          },
  /* The honest label for bytes a caller cannot name. UTType maps it to the DECLARED type
     public.data (not a dyn.*), the physical supertype of every file type above. Unmeasured
     in /Ask like everything but the first row. */
  { "application/octet-stream",  "public.data"                        },
};
#define AD_UTI_ROWS ((int)(sizeof ad_uti_table / sizeof ad_uti_table[0]))

/* MIME type -> UTI, or NULL. Case-insensitive on the type ("Image/PNG"), and anything from
   a ';' on is ignored ("text/plain; charset=utf-8"), because that is what a caller pasting
   from a web-server sketch will have in hand. */
static const char *ad_uti_from_mime(const char *mime) {
  if (!mime) return NULL;
  uint32_t n = 0;
  while (mime[n] && mime[n] != ';' && mime[n] != ' ') n++;
  if (n == 0) return NULL;
  for (int i = 0; i < AD_UTI_ROWS; i++) {
    const char *m = ad_uti_table[i].mime;
    if (strlen(m) != n) continue;
    uint32_t k = 0;
    for (; k < n; k++) {
      char a = mime[k], b = m[k];
      if (a >= 'A' && a <= 'Z') a = (char)(a - 'A' + 'a');
      if (a != b) break;
    }
    if (k == n) return ad_uti_table[i].uti;
  }
  return NULL;
}

/* Sniffed kind -> UTI, or NULL for the kinds the sniffer cannot name: OTHER, and
   APPLEDOUBLE, which is a metadata sidecar and not a file anybody sends on its own. */
static const char *ad_uti_from_sniff(int kind) {
  switch (kind) {
    case AD_FILE_JPEG: return "public.jpeg";
    case AD_FILE_PNG:  return "public.png";
    case AD_FILE_GIF:  return "com.compuserve.gif";
    case AD_FILE_HEIC: return "public.heic";     /* mif1/msf1 brands land here too; pass
                                                    image/heif if the peer should see that */
    case AD_FILE_PDF:  return "com.adobe.pdf";
    case AD_FILE_ZIP:  return "public.zip-archive";  /* also what a .docx or .key IS, physically;
                                                        pass its own type to say more */
    default:           return NULL;
  }
}

/* The reverse, for the contradiction check: which sniffable kind does this UTI CLAIM to
   be? AD_FILE_OTHER means "not something the sniffer can judge", never "unknown type". */
static int ad_uti_sniff_kind(const char *uti) {
  if (!strcmp(uti, "public.jpeg"))        return AD_FILE_JPEG;
  if (!strcmp(uti, "public.png"))         return AD_FILE_PNG;
  if (!strcmp(uti, "com.compuserve.gif")) return AD_FILE_GIF;
  if (!strcmp(uti, "public.heic") || !strcmp(uti, "public.heif")) return AD_FILE_HEIC;
  if (!strcmp(uti, "com.adobe.pdf"))      return AD_FILE_PDF;
  if (!strcmp(uti, "public.zip-archive")) return AD_FILE_ZIP;
  return AD_FILE_OTHER;
}

/* What a UTI looks like, so a typo does not go out on the wire as a type: reverse-DNS,
   ASCII, no whitespace, no '/', at least one '.', 1..AD_UTI_MAX bytes. This does NOT check
   that Apple declares it -- there is no list of those here -- only that it is shaped like
   one. Case is passed through untouched. */
static bool ad_uti_plausible(const char *s) {
  uint32_t n = 0; bool dot = false;
  for (; s[n]; n++) {
    unsigned char c = (unsigned char)s[n];
    if (n >= AD_UTI_MAX) return false;
    if (c <= ' ' || c >= 0x7F || c == '/') return false;
    if (c == '.') dot = true;
  }
  return n > 0 && dot;
}

enum { AD_UTI_OK = 0,
       AD_UTI_UNKNOWN,     /* NULL type and unsniffable bytes, or a MIME type not in the table */
       AD_UTI_MISMATCH,    /* the bytes are one sniffable kind and the type names another    */
       AD_UTI_MALFORMED }; /* a type with no '/' that is not shaped like a UTI                */

enum { AD_UTI_HOW_SNIFFED = 0, AD_UTI_HOW_MIME, AD_UTI_HOW_GIVEN };

/* Decide the UTI for one file. `type` is the caller's field: NULL, a MIME type, or a UTI.
 * On AD_UTI_OK, *out is the UTI to declare -- a string in this table, or the caller's own
 * (BORROWED, so it must outlive the send, like data) -- and *how says which.
 *
 * THE ONE RULE ABOUT THE BYTES. The sniffer always runs. If it recognises the bytes as one
 * of its six kinds and the declared type names a DIFFERENT one of those six, that is a
 * provable mislabel and it is refused -- "image/png" over a JPEG, the exact thing the old
 * PNG-only gate existed to prevent. If either side is outside the six there is nothing to
 * compare: "text/plain" over bytes the sniffer calls OTHER is trusted, and so is
 * "application/octet-stream" over a PNG, because a PNG is data. */
static int ad_uti_resolve(const char *type, const uint8_t *data, uint32_t len,
                          const char **out, int *how) {
  int sniffed = ad_cpio_sniff(data, len);
  const char *uti;
  if (!type) {
    uti = ad_uti_from_sniff(sniffed);
    if (!uti) return AD_UTI_UNKNOWN;
    *how = AD_UTI_HOW_SNIFFED;
  } else if (strchr(type, '/')) {
    uti = ad_uti_from_mime(type);
    if (!uti) return AD_UTI_UNKNOWN;
    *how = AD_UTI_HOW_MIME;
  } else {
    if (!ad_uti_plausible(type)) return AD_UTI_MALFORMED;
    uti = type;
    *how = AD_UTI_HOW_GIVEN;
  }
  int claimed = ad_uti_sniff_kind(uti);
  if (sniffed != AD_FILE_OTHER && claimed != AD_FILE_OTHER && sniffed != claimed)
    return AD_UTI_MISMATCH;
  *out = uti;
  return AD_UTI_OK;
}

static const char *ad_uti_how_name(int how) {
  switch (how) {
    case AD_UTI_HOW_SNIFFED: return "sniffed";
    case AD_UTI_HOW_MIME:    return "mime";
    case AD_UTI_HOW_GIVEN:   return "given";
    default:                 return "?";
  }
}
