#!/usr/bin/env bash
# Regenerate testdata/uti_golden.inc from Apple's UniformTypeIdentifiers framework.
#
# WHY A GOLDEN AND NOT A HAND-WRITTEN LIST. core/ad_uti.h claims each row is "the
# identifier Apple's own system uses for that MIME type". A test that compares the table
# against a list somebody typed proves only that two hand-written lists agree. This asks
# the framework, the same standard tools/gen_bplist_golden.sh holds itself to with plistlib
# and tools/test-pack.sh with cpio(1). Needs a Swift toolchain; so does nothing else here,
# which is why the .inc is committed and this script is run only when the table changes.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"
cd "$ESP32DROP_ROOT"
MIMES=$(sed -n 's/^  { *"\([a-z0-9/+.-]*\)", *".*$/\1/p' ESP32Drop/src/airdrop/core/ad_uti.h)
{
  echo "/* Generated by tools/gen_uti_golden.sh from Apple's UniformTypeIdentifiers"
  echo "   framework on $(sw_vers -productName) $(sw_vers -productVersion) ($(uname -sr))."
  echo "   Do not edit: rerun the script. Each row is UTType(mimeType:).identifier. */"
  for m in $MIMES; do
    printf '%s\n' "$m"
  done | while read -r m; do
    cat > /tmp/uti_row.swift <<SWIFT
import UniformTypeIdentifiers
if let t = UTType(mimeType: "$m") { print(t.identifier); print(t.isDynamic) } else { print(""); print("true") }
SWIFT
    out=$(swift /tmp/uti_row.swift)
    id=$(echo "$out" | sed -n 1p); dyn=$(echo "$out" | sed -n 2p)
    [[ "$dyn" == "false" ]] || { echo "FAIL: $m has no static identifier ($id)" >&2; exit 2; }
    printf '  { "%s", "%s" },\n' "$m" "$id"
  done
} > testdata/uti_golden.inc
echo "wrote testdata/uti_golden.inc ($(grep -c '^  {' testdata/uti_golden.inc) rows)"
