"""Emit C arrays of reference bplist00 bytes, straight from plistlib."""
import plistlib

CASES = [
    ("discover_m5",   {"ReceiverComputerName": "M5 Badge",
                       "ReceiverMediaCapabilities": b'{"Version":1}',
                       "ReceiverModelName": "M5Stack"}),
    ("ask_m5",        {"ReceiverComputerName": "M5 Badge",
                       "ReceiverModelName": "M5Stack"}),
    ("name_len14",    {"ReceiverComputerName": "A" * 14,
                       "ReceiverModelName": "M5Stack"}),
    ("name_len15",    {"ReceiverComputerName": "A" * 15,
                       "ReceiverModelName": "M5Stack"}),
    ("name_len16",    {"ReceiverComputerName": "A" * 16,
                       "ReceiverModelName": "M5Stack"}),
    ("name_empty",    {"ReceiverComputerName": "",
                       "ReceiverModelName": "M5Stack"}),
    ("name_ja",       {"ReceiverComputerName": "リビングのバッジ",
                       "ReceiverModelName": "M5Stack"}),
    ("name_ja_long",  {"ReceiverComputerName": "あ" * 15,
                       "ReceiverModelName": "M5Stack"}),
    ("name_emoji",    {"ReceiverComputerName": "badge \U0001F431",
                       "ReceiverModelName": "M5Stack"}),
    ("one_pair",      {"ReceiverComputerName": "solo"}),
    # Integers, for the SEND path. A real macOS sender's /Discover
    # request body is {SenderRecordData: <data>, DeviceSupportFlags: 111611} -- measured
    # off the air. The widths bracket plistlib's own choice of the
    # smallest encoding, which is what makes a byte-exact comparison meaningful.
    ("int_dsf",       {"DeviceSupportFlags": 111611}),          # 4 bytes
    ("int_0",         {"DeviceSupportFlags": 0}),               # 1 byte
    ("int_255",       {"DeviceSupportFlags": 255}),             # 1 byte, the boundary
    ("int_256",       {"DeviceSupportFlags": 256}),             # 2 bytes, the other side
    ("int_65535",     {"DeviceSupportFlags": 65535}),           # 2 bytes
    ("int_65536",     {"DeviceSupportFlags": 65536}),           # 4 bytes
    ("int_mixed",     {"DeviceSupportFlags": 111611,
                       "SenderRecordData": b"\x30\x80\x06\x09"}),
    # Nested containers, for the SEND path's nested writer (ad_bpw_*). A real /Ask body's
    # `Files` is an array of dictionaries -- measured off the air --
    # which the flat writer cannot express. These pin the two things that are not guessable
    # from the format: plistlib's flatten ORDER (container, then all keys, then all values)
    # and its DEDUPLICATION of identical scalars.
    ("nest_ask",      {"TransferID": "7246C554-E5C8-47C8-B9A5-F5CECF2FAF95",
                       "SenderComputerName": "M5 Badge",
                       "Files": [{"FileName": "card.png",
                                  "FileType": "public.png",
                                  "FileBomPath": "./card.png",
                                  "FileIsDirectory": False,
                                  "ConvertMediaFormats": False}]}),
    ("nest_dedup",    {"A": "same", "B": "same", "C": ["same", "other"]}),
    ("nest_bool",     {"T": True, "F": False}),
    ("nest_ints",     {"Items": [1, 2, 300, 70000]}),
    ("nest_deep",     {"L1": {"L2": {"L3": "leaf"}}}),
    ("nest_two_files", {"Files": [{"FileName": "a.png"}, {"FileName": "b.png"}]}),
    ("nest_ja",       {"Files": [{"FileName": "カード.png"}]}),
]

print("/* GENERATED by tools/gen_bplist_golden.sh from Python plistlib. Do not edit. */")
for name, d in CASES:
    b = plistlib.dumps(d, fmt=plistlib.FMT_BINARY, sort_keys=True)
    print(f"\n/* {name}: {d} */")
    print(f"static const unsigned char BP_{name}[] = {{")
    for i in range(0, len(b), 12):
        print("  " + ", ".join("0x%02x" % c for c in b[i:i+12]) + ",")
    print(f"}};\nstatic const unsigned int BP_{name}_len = {len(b)};")
